# Generated by Django 3.1.6 on 2021-02-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('legislature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.legislature')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.deputy')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.proposition')),
            ],
        ),
        migrations.AddField(
            model_name='deputy',
            name='legislatures',
            field=models.ManyToManyField(related_name='deputies', to='repository.Legislature'),
        ),
        migrations.AddField(
            model_name='deputy',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.party'),
        ),
    ]
