# Generated by Django 3.1.6 on 2021-03-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputy',
            options={'verbose_name_plural': 'Deputies'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
    ]
