# Generated by Django 3.1.6 on 2021-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20210326_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='title',
            new_name='title_fr',
        ),
        migrations.AddField(
            model_name='proposition',
            name='detail',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='title_nl',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
