# Generated by Django 3.1.6 on 2021-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20210326_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislature',
            name='parliament',
            field=models.CharField(choices=[('FED', 'federal'), ('BRU', 'brussels'), ('VLA', 'vlaams'), ('WAL', 'wallonia'), ('FRA', 'francophone'), ('GER', 'germanophone'), ('other', 'other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='type_code',
            field=models.CharField(choices=[('for', 'for'), ('against', 'against'), ('abstention', 'abstention'), ('absent', 'absent'), ('wait', 'wait')], default='wait', max_length=10),
        ),
    ]
