# Generated by Django 3.1.6 on 2021-12-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_party_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
